create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  assignee text not null default 'Unassigned',
  due_date date,
  priority text not null default 'Medium'
    check (priority in ('Low', 'Medium', 'High')),
  tags text[] not null default '{}',
  estimate integer not null default 1
    check (estimate > 0),
  status text not null default 'backlog'
    check (status in ('backlog', 'inProgress', 'review', 'done')),
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

drop policy if exists "Allow public read todos" on public.todos;
create policy "Allow public read todos"
  on public.todos
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Allow public insert todos" on public.todos;
create policy "Allow public insert todos"
  on public.todos
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Allow public update todos" on public.todos;
create policy "Allow public update todos"
  on public.todos
  for update
  to anon, authenticated
  using (true)
  with check (true);

insert into public.todos (name, description, assignee, due_date, priority, tags, estimate, status, order_index)
values
  (
    'Shape onboarding checklist',
    'Draft the first-run experience and add release notes copy.',
    'Avery',
    current_date + 5,
    'High',
    array['UX', 'Launch'],
    5,
    'backlog',
    0
  ),
  (
    'Polish drag interactions',
    'Tune card drop targets and motion so reprioritizing feels tactile.',
    'Kai',
    current_date + 2,
    'High',
    array['Frontend', 'UX'],
    3,
    'inProgress',
    0
  ),
  (
    'Approve mobile QA pass',
    'Confirm responsive spacing and touch targets across the board.',
    'Jules',
    current_date + 1,
    'High',
    array['QA', 'Mobile'],
    2,
    'review',
    0
  ),
  (
    'Publish component inventory',
    'Catalogued reusable UI pieces for the launch squad.',
    'Kai',
    current_date - 2,
    'Low',
    array['Design System'],
    3,
    'done',
    0
  )
on conflict do nothing;
